# Generated by Django 5.2.5 on 2026-08-07 14:41

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ShopSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Mega Fish Point', max_length=120)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('address', models.CharField(blank=True, max_length=180)),
                ('receipt_footer', models.CharField(default='Asante kwa kununua Mega Fish Point.', max_length=180)),
                ('currency', models.CharField(default='TZS', max_length=10)),
                ('low_stock_default', models.DecimalField(decimal_places=3, default=5, max_digits=14)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('electricity', 'Electricity'), ('transport', 'Transport'), ('ice', 'Ice'), ('packaging', 'Packaging'), ('rent', 'Rent'), ('salary', 'Salary'), ('cleaning', 'Cleaning'), ('other', 'Other')], default='other', max_length=30)),
                ('description', models.CharField(max_length=180)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('expense_date', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-expense_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('base_unit', models.CharField(choices=[('KG', 'KG'), ('G', 'Gram'), ('ML', 'ML'), ('PCS', 'Piece')], max_length=10)),
                ('low_stock_level', models.DecimalField(decimal_places=3, default=5, max_digits=14)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='core.category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('symbol', models.CharField(max_length=20)),
                ('conversion_to_base', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selling_units', to='core.product')),
            ],
            options={
                'ordering': ['product__name', 'conversion_to_base'],
                'unique_together': {('product', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(blank=True, max_length=120)),
                ('invoice_number', models.CharField(blank=True, max_length=80)),
                ('purchased_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('base_quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('cost_per_unit', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=14)),
                ('unit_cost_base', models.DecimalField(decimal_places=6, max_digits=18)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.product')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.purchase')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.productunit')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_no', models.CharField(blank=True, max_length=30, unique=True)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('mobile_money', 'Mobile Money'), ('bank', 'Bank')], default='cash', max_length=30)),
                ('customer_name', models.CharField(blank=True, max_length=120)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('item_discount_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('sale_discount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cogs_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('profit_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('voided', 'Voided')], default='completed', max_length=20)),
                ('sold_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.CharField(blank=True, max_length=180)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to=settings.AUTH_USER_MODEL)),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voided_sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sold_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('conversion_to_base', models.DecimalField(decimal_places=3, max_digits=14)),
                ('base_quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('normal_unit_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('line_subtotal', models.DecimalField(decimal_places=2, max_digits=14)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('final_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('cost_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('profit_before_sale_discount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.sale')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.productunit')),
            ],
        ),
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(choices=[('increase', 'Increase'), ('decrease', 'Decrease')], max_length=20)),
                ('quantity_base', models.DecimalField(decimal_places=3, max_digits=14)),
                ('reason', models.CharField(max_length=180)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='core.product')),
            ],
        ),
        migrations.CreateModel(
            name='StockBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('OPENING', 'Opening Stock'), ('PURCHASE', 'Purchase')], max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('quantity_received_base', models.DecimalField(decimal_places=3, max_digits=14)),
                ('quantity_remaining_base', models.DecimalField(decimal_places=3, max_digits=14)),
                ('unit_cost_base', models.DecimalField(decimal_places=6, max_digits=18)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='core.product')),
                ('purchase_item', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batch', to='core.purchaseitem')),
            ],
            options={
                'ordering': ['received_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SaleAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_base', models.DecimalField(decimal_places=3, max_digits=14)),
                ('unit_cost_base', models.DecimalField(decimal_places=6, max_digits=18)),
                ('cost_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('sale_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='core.saleitem')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_allocations', to='core.stockbatch')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('cashier', 'Cashier')], default='cashier', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
