# Generated by Django 5.2.5 on 2026-08-07 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopsettings',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='branding/'),
        ),
    ]
