# Generated by Django 5.2.5 on 2026-08-07 18:31

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_customer_alter_sale_payment_method_sale_customer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stocktake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_date', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('notes', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stocktakes_cancelled', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocktakes_created', to=settings.AUTH_USER_MODEL)),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stocktakes_posted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-count_date', '-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CashClosing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('close_date', models.DateField(default=django.utils.timezone.localdate)),
                ('opening_float', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('cash_sales', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('mobile_money_sales', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('bank_sales', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('debt_sales', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('debt_cash_collected', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('debt_mobile_collected', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('debt_bank_collected', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('sale_count', models.PositiveIntegerField(default=0)),
                ('debt_payment_count', models.PositiveIntegerField(default=0)),
                ('cash_paid_out', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('expected_cash', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('counted_cash', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('difference', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notes', models.CharField(blank=True, max_length=240)),
                ('closed_at', models.DateTimeField(auto_now_add=True)),
                ('amended_at', models.DateTimeField(blank=True, null=True)),
                ('amendment_reason', models.CharField(blank=True, max_length=240)),
                ('amended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_closings_amended', to=settings.AUTH_USER_MODEL)),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_closings', to=settings.AUTH_USER_MODEL)),
                ('closed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_closings_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-close_date', '-closed_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('cashier', 'close_date'), name='unique_cashier_daily_closing')],
            },
        ),
        migrations.CreateModel(
            name='StocktakeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_qty_base', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('counted_input_qty', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('count_unit_name', models.CharField(blank=True, max_length=60)),
                ('count_unit_symbol', models.CharField(blank=True, max_length=20)),
                ('count_conversion', models.DecimalField(decimal_places=3, default=1, max_digits=14)),
                ('counted_qty_base', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('difference_base', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('unit_cost_base', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('adjustment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stocktake_line', to='core.stockadjustment')),
                ('count_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stocktake_lines', to='core.productunit')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocktake_lines', to='core.product')),
                ('stocktake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.stocktake')),
            ],
            options={
                'ordering': ['product__name', 'id'],
                'constraints': [models.UniqueConstraint(fields=('stocktake', 'product'), name='unique_product_per_stocktake')],
            },
        ),
    ]
