# Generated by Django 5.2.17 on 2026-08-14 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_personalreceivable_personalreceivablepayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='base_unit',
            field=models.CharField(choices=[('PCS', 'Piece'), ('BTL', 'Bottle'), ('CARTON', 'Carton'), ('KG', 'Kilogram'), ('G', 'Gram'), ('L', 'Litre'), ('ML', 'Millilitre'), ('M', 'Metre'), ('CM', 'Centimetre'), ('M2', 'Square Metre')], max_length=10),
        ),
    ]
