# Generated by Django 5.2.17 on 2026-08-16 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_product_base_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('electricity', 'Electricity'), ('water', 'Water'), ('Food', 'Food'), ('transport', 'Transport'), ('fuel', 'Fuel'), ('rent', 'Rent'), ('salary', 'Salary / Wages'), ('loading', 'Loading & Offloading'), ('delivery', 'Customer Delivery'), ('maintenance', 'Repairs & Maintenance'), ('office', 'Office Expenses'), ('internet', 'Internet & Communication'), ('cleaning', 'Cleaning'), ('security', 'Security'), ('bank_charges', 'Bank / Mobile Money Charges'), ('licenses', 'Licenses & Permits'), ('marketing', 'Marketing / Advertising'), ('stationery', 'Stationery'), ('packaging', 'Packaging'), ('other', 'Other')], default='other', max_length=30),
        ),
    ]
